terraform-google-modules/terraform-google-project-factory

- README.md
- examples/app_engine/README.md
- examples/app_engine/main.tf
- examples/app_engine/outputs.tf
- examples/app_engine/variables.tf
- main.tf
- outputs.tf
- test/integration/gcloud/integration.bats
- test/integration/gcloud/run.sh
- test/integration/gcloud/sample.sh
- variables.tf
See https://github.com/terraform-providers/terraform-provider-google/pull/1503 for context.
Merge after: https://github.com/terraform-google-modules/terraform-google-project-factory/pull/3
> Adding new App Engine support

- test/integration/gcloud/run.sh
There are a couple of small errors in the integration testing script
causing the tests to fail.
The first is a mis-placed glob inside of a double quoted string; instead
of copying all of the files in a directory to a tempdir the test runner
tried to copy the literal file "test/integration/tmp/*", and would
subsequently fail to run terraform since no configurations were present.
This has been corrected by moving the asterisk outside of the quotes so
that it can be properly expanded.
The second issue is an omitted curly brace in the templated
`outputs.tf`, which has been restored.
> Fix errors in integration test runner script.

- main.tf
- test/integration/gcloud/integration.bats
- test/integration/gcloud/run.sh
When the project factory module was managing the default service account
membership (as set with the `sa_role` variable), it was authoritatively
managing and as a result would remove members added elsewhere. This
commit replaces the authoritative binding management with an additive
binding management.
This pull request was developed with #15 but does not include that pull
request in this branch; that branch should be merged first so that the
tests in this PR can be checked.
> Change service account IAM project membership to be additive

- main.tf
- test/integration/gcloud/integration.bats
- test/integration/gcloud/run.sh
The IAM management granting a G Suite group access to the project
factory service account was authoritative and would remove members added
elsewhere. This commit replaces the authoritative binding management
with additive binding management.
> Change service account IAM management to be additive

- main.tf
- variables.tf
Currently the `org_id` is used to get the domain name required to create / get a GSuite group named `<group_name>@<domain>`. 
The domain name is gotten using the `google_organization` resource that requires the `roles/organization.viewer` role. This resource should be activated only if `group_name` is passed. 
Currently when `group_name` is not passed, the `google_organization` resource is still called, and that will fail if for some reason one does not have the Organization Viewer role.
This PR makes `org_id` optional and adds support for a `domain` flag that will replace the it in the previous scenario, so that the project creation can still go on.
> Make `org_id` and `roles/organization.viewer` role optional

- main.tf
The `google_project_service.project_services` resource depends on
the `google_project.project` resource, but Terraform was unable to
detect this dependency though the dependencies of the variables in use.
This could lead to Terraform deleting the project and the project
services at the same time.
This commit resolves the issue by adding an explicit dependency from
`google_project_service.project_services` -> `google_project.project`.
> Add explicit dependency for google_project_service

- helpers/setup-sa.sh
While the documentation of the project clearly specifies how to use this helper script, executing this without the parameters can still be checked and help displayed to the user.  This PR aims to provide useful information when the wrong number of parameters are passed.
Validation of the provided inputs (such as wrong org or project) are handled later in the script.
> Add usage information to helper script

- docs/TROUBLESHOOTING.md
- helpers/setup-sa.sh
This adds to the helper script the optional creation of the IAM billing role for the service account that is required.  Other small changes include:
- Additional output when the hep script is run so that the user understands what steps are being executed.  This could be helpful for any debugging or failure.
- Explicit details on how to add a service account to the gcloud auth list
> Implement Billing Account Role

- examples/project-hierarchy/README.md
The project-hierarchy example requires more permissions than the ones used for the project factory; in particular, it requires folder creation. Documenting this fact and giving an example on how to add this binding.
> Improving documentation for example

- Makefile
This commit adds a make target that will print out the available make
targets and descriptions.
Running `make` results in the following text:
```
all                           Run all linters and update documentation
check_docker                  Lint Dockerfiles
check_golang                  Lint Go source files
check_headers                 Check that source files have appropriate boilerplate
check_python                  Lint Python source files
check_shebangs                Check that scripts have correct shebangs
check_shell                   Lint shell scripts
docker_converge               Run `kitchen converge` within the Docker test environment
docker_create                 Run `kitchen create` within the Docker test environment
docker_destroy                Run `kitchen destroy` …
```
> Add a `help` target to the Makefile

- README.md
> Fix readme to make app_engine api optional (Issue #23)

- main.tf
An inverted comparison caused us to not add members to the
`roles/compute.networkUser` role when shared VPC subnets were supplied.
This commit fixes the error.
Thanks to @aaron-lane for improving the test-kitchen test coverage to catch this!
> Invert comparison when managing project network membership

- main.tf
- test/fixtures/full/main.tf
- test/integration/full/controls/project-factory.rb
- test/integration/minimal/controls/minimal.rb
- variables.tf
This commit adds a `lien` variable and backing logic to add liens to
GCP projects. This allows users to prevent projects from being
unintentionally deleted.
Because the lien is a Terraform resource, it's still possible to delete
the project with an errant `terraform destroy.
> Add lien support to project-factory

- helpers/release-new-version.sh
- helpers/setup-sa.sh
sed on Linux-based systems does not understand `-i ''`.
> Use sed in cross-platform compatible manner

- test/fixtures/full/main.tf
- test/fixtures/shared/outputs.tf
- test/fixtures/shared/terraform.tfvars.example
- test/fixtures/shared/variables.tf
In order to have fully isolated tests in CI we should create all
fixtures within the tests, including the shared VPC host and network.
This commit removes the `shared_vpc` variable from the test
configurations and creates an additional project instead.
> Create shared VPC host project for integration tests

- helpers/migrate.py
- modules/core_project_factory/main.tf
This commit renames the `google_project.project` resource to distinguish
between Terraform v0.x and v1.0 and updates the migration script to
distinguish between the two migration levels.
> Make migration script idempotent

- scripts/preconditions.sh
- scripts/preconditions/preconditions.py
The preconditions script attempts to catch the FileNotFoundError
exception, which is only defined in Python3. This commit updates the
preconditions shell wrapper to search for python3 and updates the
preconditions script shebang accordingly.
> Preconditions script is python3 only

- Makefile
Commit ea33a35 introduced a typo to the `make check_terraform` target,
this commit fixes the error.
> Fix `check_terraform` make target

- modules/gsuite_enabled/main.tf
This commit patches gsuite_enabled to only manage a group when a name is
provided or the toggle to create a group is set.
> Only manage group if it is existent

- Makefile
- test/helpers/test_migrate.py
This updates the migration script test coverage to ensure that the
migrated resources is an exact match and account for dropped
data sources/unmigrated resources.
> Fix migration script test coverage

- Makefile
- test/ci_integration.sh
This commit extracts the CI setup logic into a shell script in this repository, and updates the Make targets to pass around the correct environment variables. This change allows us to more closely simulate how CI works, and allows us to iterate on the CI workflow in pull requests rather than having to manage everything within the pipeline definition.
> Move CI configuration logic to script

- .gitignore
- modules/core_project_factory/main.tf
- modules/gsuite_enabled/main.tf
- modules/gsuite_group/main.tf
- modules/gsuite_group/outputs.tf
- modules/gsuite_group/variables.tf
When a new G Suite group is created to manage a project, `core_project_factory` would attempt to assign the group IAM permissions before the group was finished being created by the `gsuite_enabled` module. To fix this condition, an implicit dependency was added to the Terraform using the email attribute from the `gsuite_group` resource.
Also, the `google_compute_default_service_account` resource depends on the Compute Engine API being enabled so it is possible for the fetch of the data resource to fail because it attempts to query the Compute Engine API before it is fully enabled. Adding an explicit dependency on the services being enabled fixes this issue.
> Fix a race condition when creating a new G Suite group

- README.md
- modules/core_project_factory/scripts/preconditions/preconditions.py
- test/scripts/preconditions/test_preconditions.py
> Drop unused permissions from preconditions script

- modules/core_project_factory/main.tf
The default service account data resource currently uses a depends_on
flag added to prevent a race condition in
https://github.com/terraform-google-modules/terraform-google-project-factory/pull/141
Due to the way that Terraform refreshes data resources, Terraform thinks
that the data resource has changed when in actuality it hasn't:
https://github.com/hashicorp/terraform/issues/11806#issuecomment-279108107
By changing to use a null data resource that interpolates the default
service account email, the data resource will only change when the project
number does.
> Stablize default service account in plan

- Makefile
These changes bring the environment setup for `docker_create`, `docker_converge`, `docker_verify`, and `docker_destroy` in line with how environment setup works for `docker_run` and `test_integration_docker`.
> Update build targets in Makefile to properly set up docker environment

- README.md
This branch fixes the name of the credentials environment variable in the README.
> Fix name of credentials env variable in README

- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/outputs.tf
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/outputs.tf
- modules/gsuite_enabled/variables.tf
- outputs.tf
- test/fixtures/full/main.tf
- test/fixtures/shared/outputs.tf
- test/integration/full/controls/project-factory.rb
- test/integration/full/inspec.yml
- test/integration/minimal/controls/minimal.rb
- variables.tf
> Allow project name to be changed separately from project ID

- README.md
- modules/core_project_factory/README.md
- modules/core_project_factory/main.tf
- modules/gsuite_enabled/README.md
- test/fixtures/full/README.md
- test/fixtures/minimal/README.md
- test/integration/full/controls/shared-vpc.rb
This commit addresses issue #97
(https://github.com/terraform-google-modules/terraform-google-project-factory/issues/97)
and updates the logic around IAM bindings with regard to shared VPC
subnets. The logic is as follows:
1. If `var.shared_vpc` and `var.shared_vpc_subnets` are empty no
bindings are mad
2. If `var.shared_vpc` is set but no subnets are provided with
`var.shared_vpc_subnets` then the IAM bindings are set at the Host
Project
3. If `var.shared_vpc` is set and `var.shared_vpc_subnets` contains
subnets then the IAM bindings are granted on the subnetworks
themselve
This commit updates the logic used to calculate the Host Project
bindings based on scenario 3 above. The tests have also been modified to
ensure that those bindings AREN'T set.
> Fix shared VPC IAM bindings

- CHANGELOG.md
This branch adds the CHANGELOG entry for v2.1.0. It also notes that v2.0.0 introduced support for v2 of the Google Terraform providers.
> Update CHANGELOG.md for v2.1.0

- test/ci_integration.sh
- test/fixtures/full/main.tf
- test/fixtures/minimal/main.tf
- test/fixtures/shared/variables.tf
Without this commit the integration test fixtures will create VPC
networks with randomized names, but the subnetwork names will remain
static. Because subnetworks are regional resources, you can't have two
subnetworks with the same name tied to the same project and region. This
means that without adding randomness to subnetwork names, only 1 run of
the integration test pipeline can occur at any given time.
Normally a random_string resource is used to impart randomness into
resource names, but the way the Network module performs lookups on the
`var.subnets` and `var.secondary_ranges` input variables, those
variables cannot contain computed values. To remedy this, the test
fixtures now include an input variable named
`var.random_string_for_testing` that accepts a string to be appended on …
> Refactor tests for randomized names

- .kitchen.yml
- test/fixtures/full/extra_outputs.tf
- test/fixtures/full/main.tf
- test/fixtures/shared_vpc_no_subnets/extra_variables.tf
- test/fixtures/shared_vpc_no_subnets/main.tf
- test/fixtures/shared_vpc_no_subnets/outputs.tf
- test/fixtures/shared_vpc_no_subnets/variables.tf
- test/integration/full/controls/shared-vpc.rb
- test/integration/full/inspec.yml
- test/integration/shared_vpc_no_subnets/controls/gcloud.rb
- test/integration/shared_vpc_no_subnets/controls/gcp.rb
- test/integration/shared_vpc_no_subnets/inspec.yml
This commit adds tests surrounding the shared VPC IAM behavior.
Specifically, we're testing whether the `compute.networkUser` role is
added to the Host Project if `var.shared_vpc` is passed but
`var.shared_vpc_subnets` is not.
> Add test for shared VPC IAM behavior

- modules/gsuite_group/main.tf
* `roles/organizationViewer` role should not be necessary if domain is specified.
* Error occurs when project factory is scoped to the folder level (i.e. no org-level permissions, only folder-level permissions)
```
data.google_organization.org: Refreshing state...
Error: Error refreshing state: 1 error(s) occurred:
* module.project-factory.module.gsuite_group.data.google_organization.org: 1 error(s) occurred:
* module.project-factory.module.gsuite_group.data.google_organization.org: data.google_organization.org: Error reading Organization Not Found : <org-id-redacted>: googleapi: Error 403: The caller does not have permission, forbidden
```
The fix disables the `data.organization` lookup when the variable `domain` is specified.
> Fix bug in gsuite_group module that requires organizationViewer role

- modules/core_project_factory/scripts/preconditions/preconditions.py
- test/integration/shared_vpc_no_subnets/inspec.yml
Instead of throwing a KeyError like this:
```
* module.project-factory.module.project-factory.null_resource.preconditions: Error running command '/cft/workdir/test/fixtures/minimal/.terraform/modules/76c2ddba7cd279abe2254470a2c70bac/scripts/prec
onditions.sh \
--credentials_path '' \
--billing_account '<redacted>' \
--org_id '<redacted>' \
--folder_id '<redacted>' \
--shared_vpc ''
': exit status 1. Output: Traceback (most recent call last):
File "/cft/workdir/test/fixtures/minimal/.terraform/modules/76c2ddba7cd279abe2254470a2c70bac/scripts/preconditions/preconditions.py", line 455, in <module>
retcode = main(sys.argv)
File "/cft/workdir/test/fixtures/minimal/.terraform/modules/76c2ddba7cd279abe2254470a2c70bac/scripts/preconditions/preconditions.py", line 437, in main …
```
> fix KeyError when billing permission requirements are unsatisfied

- modules/core_project_factory/scripts/preconditions/preconditions.py
- test/scripts/preconditions/test_preconditions.py
This org-level permission is not required in most cases - it is only required for the `gsuite_group` module when "domain" is not specified. Enhancement to add this conditional verification to the `gsuite_group` module will be handled in a subsequent, separate PR.
> remove permission check for resourcemanager.organization.get

- examples/shared_vpc/README.md
- examples/shared_vpc/main.tf
- examples/shared_vpc/outputs.tf
- examples/shared_vpc/variables.tf
- modules/core_project_factory/outputs.tf
This PR:
- Adds an example of combining the project factory and shared VPC modules to create a host project
- Fixes https://github.com/terraform-google-modules/terraform-google-network/issues/15 by making the project ID output depend on project service activation
> Add Shared VPC example and fix dependencies

- CHANGELOG.md
- README.md
- main.tf
- modules/core_project_factory/README.md
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/variables.tf
- modules/project_services/README.md
- modules/project_services/main.tf
- modules/project_services/variables.tf
- variables.tf
The argument/variable that manages disable_dependent_services has been added
> disable_dependent_services argument/variable have been added

- .pre-commit-config.yaml
I find pre-commit useful in that it won't let me commit if terraform is not properly formatted or docs need to be updated.
> feat: add pre-commit to automatically format and create docs

- CHANGELOG.md
- examples/shared_vpc/main.tf
Versions for providers has been fixed for examples/shared_vpc
> required versions of providers added to shared_vpc

- modules/fabric-project/README.md
- modules/fabric-project/main.tf
- modules/fabric-project/outputs.tf
This adds a simple computed output to expose the cloudservices service account in the fabric submodule outputs, as a convenience when [setting project service access for GKE to shared VPC subnets](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-shared-vpc#summary_of_roles_granted_on_subnets).
> Add the cloudservices service account output to the fabric submodule

- modules/core_project_factory/outputs.tf
- modules/gsuite_enabled/variables.tf
This commit ensures that `project_id` blocks on the authoritative project services if enabled.
> Add `project_services_authority` to `project_id`

- README.md
- helpers/setup-sa.sh
#192 
- Added minimum permissions required to run setup.sh into README.MD
- Auto-formatted README.MD
- Added billing account to the list of arguments for setup.sh into README.MD
> Fixes #192 Permissions required by setup-sa.sh not documented

- modules/fabric-project/main.tf
In Terraform 12 booleans are not converted to number automatically. This pull request fixes it.
> fixes bug introduced by tf12 in fabric-project. Bool to number conversion

- modules/fabric-project/README.md
- modules/fabric-project/main.tf
- modules/fabric-project/variables.tf
In order to make it easy to use factory-project submodule in combination with https://github.com/terraform-google-modules/terraform-google-folders
> Deprecate 'parent_type' and 'parent_id' input variables 

- CHANGELOG.md
- Makefile
- examples/app_engine/main.tf
- examples/gke_shared_vpc/main.tf
- examples/group_project/main.tf
- examples/project-hierarchy/main.tf
- examples/shared_vpc/main.tf
- examples/simple_project/main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/scripts/preconditions/preconditions.py
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/main.tf
- modules/shared_vpc/main.tf
- modules/shared_vpc/outputs.tf
- modules/shared_vpc/variables.tf
- test/fixtures/full/main.tf
- test/fixtures/shared/variables.tf
- test/fixtures/shared_vpc_no_subnets/main.tf
- test/make.sh
- variables.tf
Fixes https://github.com/terraform-google-modules/terraform-google-project-factory/issues/47
> Fixes for issuue #47

- modules/core_project_factory/main.tf
previously it wasn't possible to create the project bucket within the project as the project wouldn't exist or wouldn't have the expected random suffix.  This will detect the intent to create the bucket in the project we are creating and use the project's id.
> allow creation of project_bucket within the project we are creating.

- README.md
- docs/TROUBLESHOOTING.md
* Remove no longer relevant reference to `app_engine` input from README.md
* Provide context for mysterious "Internal Server Error" when deploying App Engine Flex application with `gcloud` to project missing its default compute engine service account.
> Clarify Documentation regarding App Engine

- README.md
The version of project-factory referenced in the repository README is not up to date. Using it in practice with Terraform 0.12 causes errors:
```
Downloading modules/core_project_factory for project.project-factory...
Error: Module not found
The module address "modules/gsuite_group" could not be resolved.
If you intended this as a path relative to the current module, use
"./modules/gsuite_group" instead. The "./" prefix indicates that the address
is a relative filesystem path.
Error: Module not found
The module address "modules/core_project_factory" could not be resolved.
If you intended this as a path relative to the current module, use
"./modules/core_project_factory" instead. The "./" prefix indicates that the
address is a relative filesystem path.
```
> Update project-factory version referenced in repository README

- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/variables.tf
Passes impersonate_service_account through to the core module from gsuite_enabled module.
Fixes https://github.com/terraform-google-modules/terraform-google-project-factory/issues/285
> Passing impersonate_service_account through to core module

- README.md
- docs/upgrading_to_project_factory_v4.0.md
- helpers/migrate4.py
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/outputs.tf
- modules/core_project_factory/variables.tf
- modules/fabric-project/main.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/variables.tf
- modules/project_services/main.tf
- modules/project_services/outputs.tf
- modules/shared_vpc/main.tf
- modules/shared_vpc/variables.tf
- variables.tf
Convert the project_services module to use for_each instead of count,
and use that module in the core project factory.
Remove the var.apis_authority option.
Add to helpers/migrate.py to also convert this project services
migration. The old GSuite migration will still work. To make this
migration work, it needs to read a value from a resource, which means
calling terraform state show, which is slow.
This is heavily blocked by hashicorp/terraform#22301, as the migrate
script fails to state move the instances of count to instances of
for_each without the for_each resource existing first. As it is, the
migrate script fails with this error:
```
Cannot move to
module.my-project.module.project-factory.module.project_services.google_project_service.project_services["cloudbilling.googleapis.com"]: …
```
> Use project_services module and convert to for_each

- README.md
- modules/project_services/README.md
Add the upgrade guide to the main README.
Update the required Terraform version to 0.12.6, since that is the
oldest version that supports `for_each`.
In all examples, update used version to 4.0.
> Update README versions to 4.0

- README.md
The current version of the module requires terraform 0.12.6+.
0.12.6 is the version the introduced `for_each` which is in the [project services resource](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/ac41dd3159b2751e3c2ec362f69c66e20a607c33/modules/project_services/main.tf#L21).
> Update terraform binary requirement

- modules/project_services/outputs.tf
If the activate_apis variable was set to an empty list, the
project_services module would crash on trying to get the 0 index of the
empty list. Fix is to instead of only returning the project id from the
input if the enable_apis is false, just concat that variable to the
list, so if there is nothing else in the list, that is returned.
Fixes #300
> Fix module crash on empty api list

- helpers/setup-sa.sh
`FOLDER_ID` is used at line 136, so the variable not being set is causing issues. Set it to blank, or attempt to set it in existing project folder if statement
Addresses #316
> Update setup-sa.sh to set FOLDER_ID

- CHANGELOG.md
- README.md
- examples/simple_project/README.md
- examples/simple_project/variables.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/scripts/modify-service-account.sh
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/variables.tf
- modules/shared_vpc/variables.tf
- test/fixtures/full/README.md
- test/fixtures/full/main.tf
- test/fixtures/minimal/README.md
- test/fixtures/minimal/main.tf
- test/fixtures/shared/outputs.tf
- test/integration/full/controls/project-factory.rb
- test/integration/full/inspec.yml
- test/integration/minimal/controls/minimal.rb
- test/integration/minimal/inspec.yml
- variables.tf
Disabling instead of deleting the default service account achieves the
same result: the service account no longer works. But disabling is
possible to undo at any time, where after 30 days a deleted account is
unrecoverable.
I have tested this with creating a new project, and it works as expected.
Thoughts about making this the default instead of delete?
Resolves #313
> Add option to disable default compute SA

- CHANGELOG.md
- README.md
- docs/TROUBLESHOOTING.md
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/variables.tf
- modules/shared_vpc/variables.tf
- variables.tf
This is a better option than "delete", since it has the same outcome
(the account doesn't work), but it is possible to get the account back,
unlike which delete which can be unrecoverable. This then should be the
default, since it achieves the same outcome, but is completely and
easily reversible for those that realize they don't want the default
later on.
Related #313, #314
> Change default for default compute SA to disable

- modules/core_project_factory/scripts/modify-service-account.sh
When `default_service_account`=`delete`, deprivilege first to remove IAM binding before deleting the service account.
Fixes #339
> Deprivilege before deleting service account

- CHANGELOG.md
- README.md
- examples/simple_project/main.tf
- modules/app_engine/versions.tf
- modules/core_project_factory/versions.tf
- modules/gsuite_group/versions.tf
- modules/project_services/versions.tf
- test/fixtures/minimal/main.tf
Fixes #346 
- Updated provider version in all modules to `>= 2.1, < 4.0`
- Updated example and simple test to use current 3.3.0 version
- Verified on [Upgrade Guide](https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html) that all resources and configs in all modules don't have backwards incompatible setups.
> relax google provider versioning. Allow for 3.x

- README.md
We got a question about what a seed project is in Slack, and the glossary is a little hard to spot once you're already reading the docs.
> Directly link to the glossary for seed project/SA

- CHANGELOG.md
- Makefile
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- modules/core_project_factory/main.tf
> Don't fail if precondition fails

- .kitchen.yml
- examples/shared_vpc/README.md
- examples/shared_vpc/main.tf
- examples/shared_vpc/outputs.tf
- modules/core_project_factory/main.tf
- test/fixtures/dynamic_shared_vpc/main.tf
- test/fixtures/dynamic_shared_vpc/outputs.tf
- test/fixtures/dynamic_shared_vpc/variables.tf
- test/integration/dynamic_shared_vpc/controls/svpc.rb
- test/integration/dynamic_shared_vpc/inspec.yml
- test/setup/iam.tf
This should prevent issues from occurring around the dynamically created/managed subnets or shared VPC host projects.
> chore: Add a test fixture to validate dynamic Shared VPC

- examples/gke_shared_vpc/variables.tf
Follow up on #382 to fix issue in example.
Fixes #384
> Fix shared_vpc_subnets default on gke_shared_vpc example

- README.md
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/variables.tf
- modules/shared_vpc/main.tf
- modules/shared_vpc/variables.tf
- variables.tf
> Add use_tf_var_google_credentials_env_var variable

- modules/core_project_factory/outputs.tf
- test/fixtures/minimal/README.md
- test/fixtures/minimal/main.tf
- test/fixtures/minimal/outputs.tf
- test/integration/minimal/controls/minimal.rb
- test/integration/minimal/inspec.yml
Adds a dependency on project services to the output project id and
number.  This prevents a race for using a robot account based on the
project id or number, as the robot accounts can be created only when
the service enabling is finished.
Fixes #386
> Add dependency on service enablement.

- CHANGELOG.md
- README.md
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/variables.tf
- modules/shared_vpc/main.tf
- modules/shared_vpc/variables.tf
- variables.tf
Adds ability to skip the downloading of the gcloud CLI. Exposing this functionality is important to us because:
- the download functionality adds a lot of unnecessary overhead when running in our ci pipeline which runs in a container image with gcloud pre-installed
- the resources it adds to the terraform plan make the plan harder to read
- it seems to scale not so well with the amount of projects because the gcloud cli is installed once for every module instance instead of once overall
Similar to https://github.com/terraform-google-modules/terraform-google-project-factory/pull/369. However, that PR semms to contain other unreleated changes
> Add option for skipping the gcloud CLI download

- modules/core_project_factory/main.tf
This PR bumps the terraform-google-gcloud module to the newly release 1.0.0 version. I'm eager to try this out on our project. Big thanks to everyone involved!
Related issue: https://github.com/terraform-google-modules/terraform-google-project-factory/issues/396
Related issue on the terraform-google-gcloud https://github.com/terraform-google-modules/terraform-google-gcloud/issues/37
> Bump version of terraform-google-gcloud module to 1.0.0

- docs/upgrading_to_project_factory_v8.0.md
It will confuse users if we ask them to set a variable which doesn't exist. Note: `skip_download` is a variable of `terraform-google-modules/gcloud/google` not `terraform-google-modules/project-factory/google`.
> fix docs to correct skip_gcloud_download var

- modules/core_project_factory/scripts/preconditions/preconditions.py
Fixes #389 
Since app engine has been moved into its own submodule, this check is no longer required.
> Remove appengine.googleapis.com from required APIs

- modules/core_project_factory/scripts/modify-service-account.sh
> Fix #414: Use exact match for roles/editor in removing default binding

- helpers/setup-sa.sh
> fix: Correct SA custom name flag check in setup

- examples/shared_vpc/main.tf
- modules/core_project_factory/outputs.tf
Wait for `google_compute_shared_vpc_service_project` to resolve before output `project_id`
> fix: Add dependency on svpc

- README.md
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/variables.tf
- modules/shared_vpc/main.tf
- modules/shared_vpc/variables.tf
- variables.tf
Since GCS bucket created withing project creating is mostly used for Terraform state storing, enable versioning is highly recommended for it.
This PR provides `bucket_versioning` key to enable versioning, however disables versioning by default for compatibility.
> feat: Enable GCS bucket versioning

- docs/upgrading_to_project_factory_v9.0.md
- examples/shared_vpc/main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/outputs.tf
- modules/project_services/README.md
- modules/shared_vpc/main.tf
- modules/shared_vpc/outputs.tf
- modules/shared_vpc_access/README.md
- modules/shared_vpc_access/main.tf
- modules/shared_vpc_access/outputs.tf
- modules/shared_vpc_access/variables.tf
- modules/shared_vpc_access/versions.tf
- test/integration/dynamic_shared_vpc/controls/svpc.rb
This submodule is used to control access of the API service accounts
on the host project. Service Accounts are given appropriate permissions
based on the list of active apis. The module is meant to be extended in
the future with more support for API service accounts.
Note: I have set `skip_gcloud_download  = "true"` in `examples/shared_vpc/main.tf` 
to speed up integration testing.
> Creating shared_vpc_access submodule

- examples/app_engine/versions.tf
- examples/budget_project/versions.tf
- examples/fabric_project/versions.tf
- examples/gke_shared_vpc/versions.tf
- examples/group_project/versions.tf
- examples/project-hierarchy/versions.tf
- examples/project_services/versions.tf
- examples/shared_vpc/versions.tf
- examples/simple_project/versions.tf
- modules/app_engine/versions.tf
- modules/budget/versions.tf
- modules/core_project_factory/versions.tf
- modules/fabric-project/versions.tf
- modules/gsuite_enabled/versions.tf
- modules/gsuite_group/versions.tf
- modules/project_services/versions.tf
- modules/shared_vpc/versions.tf
- modules/shared_vpc_access/versions.tf
- test/fixtures/fabric_project/versions.tf
- test/fixtures/full/versions.tf
- test/fixtures/minimal/versions.tf
- test/fixtures/shared_vpc_no_subnets/versions.tf
- test/fixtures/vpc_sc_project/versions.tf
- test/setup/versions.tf
- versions.tf
- relax version constraint to allow usage with 0.13
- Kitchen tests [run with `v0.13.0-rc1`](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/commit/88017ad3bc0d40473ac3d94546660328aeee878d) 
- `minimal-local`, `fabric-project-local`, `app-engine-local`, `budget-local` passed
- `vpc-sc-project-local`, `dynamic_shared_vpc` failed due to dependencies on other modules with version constraints
- module `for_each` and `depends_on` spot checked and seems to be working without issues
> chore: relax tf version to allow 0.13

- Makefile
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- modules/shared_vpc_access/main.tf
- modules/shared_vpc_access/outputs.tf
- test/fixtures/dynamic_shared_vpc/outputs.tf
- test/integration/dynamic_shared_vpc/controls/svpc.rb
- test/integration/dynamic_shared_vpc/inspec.yml
- test/setup/main.tf
- fix svpc regression to grant `roles/compute.networkUser` at project level if subnets empty
- additional tests to cover all cases
- if list of subnets empty, expect GKE/dataproc  bindings at project level (`service project b`)
-  if list of subnets not empty, expect GKE/dataproc bindings at subnet level (`service project`)
- Either case, if GKE,  `roles/container.hostServiceAgentUser` granted at project level
- use common resources for each service
> bug: fix svpc regression

- modules/core_project_factory/main.tf
- variables.tf
https://github.com/terraform-google-modules/terraform-google-gcloud/releases/tag/v2.0.0
>The module has been changed to not download gcloud by default. You can override this behavior by setting skip_download = false or setting the GCLOUD_TF_DOWNLOAD environment variable to "always".
~Also setting `skip_gcloud_download` to true by default~
> Upgrade gcloud module to 2.0.0

- build/int.cloudbuild.yaml
Recently CI for PF seems to be failing at the destroy step. For instance #450 
I have been unable to repro locally but my theory is that it is due to multiple gcloud destroys happening in the same build step. This aims to build them in separate build steps in parallel. 
edit: that alone did not solve the problem completely, ended up skipping gcloud for all but one example
Changelist
- parallel builds
- added global `GCLOUD_TF_DOWNLOAD=always`
- set `GCLOUD_TF_DOWNLOAD=never` for minimal example
> [DRAFT] chore: parallel builds for int tests

- examples/shared_vpc/main.tf
- modules/shared_vpc_access/README.md
- modules/shared_vpc_access/main.tf
- test/fixtures/full/main.tf
- test/fixtures/shared_vpc_no_subnets/main.tf
- test/integration/dynamic_shared_vpc/controls/svpc.rb
- test/integration/full/controls/shared-vpc.rb
- test/integration/shared_vpc_no_subnets/controls/gcloud.rb
Add Dataflow API service account to Shared VPC host project if API is enabled on new projects. see https://cloud.google.com/dataflow/docs/concepts/security-and-permissions#cloud_dataflow_service_account
> feat: Add Dataflow to Shared VPC API service accounts

- README.md
- main.tf
- modules/budget/README.md
- modules/budget/main.tf
- modules/budget/variables.tf
- variables.tf
Allow configuring billing budget with monitoring notification channels.
Fixes https://github.com/terraform-google-modules/terraform-google-project-factory/issues/455
> Add budget notification channel

- README.md
- examples/shared_vpc/main.tf
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/outputs.tf
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/variables.tf
- modules/shared_vpc/main.tf
- test/fixtures/full/versions.tf
- variables.tf
@morgante @bharathkkb After two PRs (#459 and #464) I hope I finally did the right thing 😅
> [Features] Create project as SVPC host project

- modules/project_services/main.tf
```
Warning: Interpolation-only expressions are deprecated
on .terraform/modules/project-assets/modules/project_services/main.tf line 57, in resource "google_project_iam_member" "project_service_identity_roles":
57:   member  = "serviceAccount:${google_project_service_identity.project_service_identities["${each.value.api}"].email}"
```
> fix tf12+ warning

- README.md
- outputs.tf
these were previously added to `core_project_factory` but not re-exported by top level module
useful for people who prefer to use the top level module instead of core_project_factory
> add apis related outputs to main module

- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/variables.tf
- modules/shared_vpc/main.tf
- modules/shared_vpc/variables.tf
Pass through budget_monitoring_notification_channels to all modules which include the budget module.
> Add budget_monitoring_notification_channels to modules including budgets

- examples/gke_shared_vpc/main.tf
- examples/shared_vpc/main.tf
- modules/shared_vpc/main.tf
- modules/shared_vpc_access/README.md
- modules/shared_vpc_access/main.tf
- modules/shared_vpc_access/variables.tf
> fix: support passing service project number to shared_vpc_access to be tf 0.13 compatible

- examples/app_engine/versions.tf
- examples/budget_project/versions.tf
- examples/fabric_project/versions.tf
- examples/gke_shared_vpc/versions.tf
- examples/group_project/versions.tf
- examples/project-hierarchy/versions.tf
- examples/project_services/versions.tf
- examples/shared_vpc/versions.tf
- examples/simple_project/versions.tf
- modules/app_engine/versions.tf
- modules/budget/versions.tf
- modules/core_project_factory/versions.tf
- modules/fabric-project/versions.tf
- modules/gsuite_enabled/versions.tf
- modules/gsuite_group/versions.tf
- modules/project_services/versions.tf
- modules/shared_vpc/versions.tf
- modules/shared_vpc_access/versions.tf
- test/fixtures/fabric_project/versions.tf
- test/fixtures/full/versions.tf
- test/fixtures/minimal/versions.tf
- test/fixtures/shared_vpc_no_subnets/versions.tf
- test/fixtures/vpc_sc_project/versions.tf
- test/setup/versions.tf
- versions.tf
This PR adds support for terraform 0.14.
This PR just bumps the version I haven't been able to test in my setup - I assume however it works as per https://github.com/terraform-google-modules/terraform-google-sql-db/pull/165#issue-531627730.
> chore(terraform): support terraform 0.14 by bumping version constraint to v0.15

- docs/upgrading_to_project_factory_v10.0.md
- modules/svpc_service_project/README.md
- modules/svpc_service_project/versions.tf
- fix svpc_service_project missing module rename
- Adds information on renamed vars in 10.0 upgrade guide
> Add renaming info to upgrade guide 10.0 

- main.tf
Fixes https://github.com/terraform-google-modules/terraform-google-project-factory/issues/519
> fix: pass service project num to shared_vpc_access in root module

- README.md
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- variables.tf
This PR adds support for adding labels to the bucket
> feat: Add labels support to projects bucket

- README.md
- main.tf
- modules/svpc_service_project/README.md
- modules/svpc_service_project/main.tf
- modules/svpc_service_project/variables.tf
- variables.tf
It's supported already in the shared_vpc_access submodule but not
available in upper modules. It should be exposed so caller of project
factory modules can leverage this feature.
> feat: expose grant_services_security_admin_role var

- README.md
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/variables.tf
- modules/svpc_service_project/README.md
- modules/svpc_service_project/main.tf
- modules/svpc_service_project/variables.tf
- variables.tf
Make the creation of the service account more flexible, allowing the name change.
> feat: add default service account name

- modules/shared_vpc_access/main.tf
Composer needs role _composer.sharedVpcAgent_ or _networkAdmin_ at the project level because of peering. Therefore, this hotfix separetes the role in another resource in the same way that we are implementing it in the gke agent.
> fix: Composer shared vpc

- README.md
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- variables.tf
Adding a `bucket_force_destroy` variable to allow `terraform destroy` to be run on this module more gracefully.
At the moment if any objects are left in the GCS bucket, running terraform destroy results in an error:
```
Error: Error trying to delete bucket <bucket name> containing objects without `force_destroy` set to true
```
The default value of the new variable is false, so there is no change in functionality without setting `bucket_force_destroy` to true.
> Add force_destroy option to GCS bucket

- modules/quota_manager/versions.tf
The root module support `>= 0.13.0`. There is no reason for one single module to break for existing users on Terraform 0.14, especially with the new release.
I have set it to be consistent with the root module.
> Change Quota Manager Terraform Required Version

- modules/core_project_factory/outputs.tf
I ran into a case where somehow `google_compute_shared_vpc_service_project.shared_vpc_attachment` was an "empty tuple" in the state, and this output was failing because it was trying to index into it. I came across https://github.com/hashicorp/terraform/issues/25578, which might be related, but it does still happen with the latest version of Terraform as of opening this bug (v0.14.9).
Regardless, it seems to me that all this is doing is building a list then taking the first element, so the one-liner should be equivalent and avoids this error.
> Simplify project_id output in core_project_factory

- modules/core_project_factory/versions.tf
* Allowing newer versions of null/random provider
* Newer versions of nul//random support Mac M1 natively
Fixed #582
> Adding Support for Mac M1 (Upgrade null/random versions)

- README.md
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- variables.tf
Fixes #586 
Adding a variable to enable uniform-bucket-level access on the project bucket if users wish to.
Default is kept false so no change to integration tests, the module remains the same in the default config
This is considered a [policy](https://docs.accurics.com/projects/accurics-terrascan/en/latest/policies/gcp/) violation by terrascan on accurics.gcp.IAM.122
P.S I know we can turn off the bucket creation but I would rather not do the same every time I want to make a project with this module
> feat: add support for uniform_bucket_level_access

- test/fixtures/budget/outputs.tf
- test/integration/budget/controls/budget.rb
- test/integration/budget/inspec.yml
fixes https://github.com/terraform-google-modules/terraform-google-project-factory/issues/588
> fix: billing budget tests

- README.md
- main.tf
- variables.tf
Hello, this PR allows the user to customize the budget display name, as it is already allowed by the budget submodule.
Thanks.
> feat: allow budget display name customization

- modules/core_project_factory/main.tf
This fixes #607
Service project needs to be added to the VPC-SC perimeter before it get attached to the SharedVPC (that is part of the same VPC-SC Perimeter) else you get a `Error 403: Request is prohibited by organization's policy. vpcServiceControlsUniqueIdentifier`
Adding `google_access_context_manager_service_perimeter_resource.service_perimeter_attachment[0]` to `depends_on` for  `"google_compute_shared_vpc_service_project" "shared_vpc_attachment"` doesn't work either as the VPC-SC api seems to be eventually consistent.
Adding a 5s `time_sleep` although not ideal fixes the issue.
> added time_sleep and dependancies on shared vpc attachment

- modules/shared_vpc_access/main.tf
This grants Serverless VPC Access Service Agent compute.networkUser role on subnetworks which are required for it to function.
https://cloud.google.com/run/docs/configuring/connecting-shared-vpc#grant-permissions
> Give VPC Access Agent Service Account Permissions

- README.md
- examples/shared_vpc/README.md
- examples/shared_vpc/main.tf
- examples/shared_vpc/outputs.tf
- modules/shared_vpc_access/README.md
- modules/shared_vpc_access/main.tf
- modules/shared_vpc_access/variables.tf
- modules/svpc_service_project/README.md
- modules/svpc_service_project/main.tf
- modules/svpc_service_project/variables.tf
- test/fixtures/dynamic_shared_vpc/outputs.tf
- test/integration/dynamic_shared_vpc/controls/svpc.rb
- test/integration/dynamic_shared_vpc/inspec.yml
- variables.tf
Added a new flag (grant_services_network_role) to control whether service project service accounts are granted the roles/compute.networkUser on the shared VPC host project. The default value for this flag is true for backwards compatibility.
- Added the flag
- Added integration tests
- Updated documentation
fixes #603
> feat: added the grant_services_network_role flag to control network IAM

- main.tf
Looks like we forgot to add this to the root module in #618
> fix: plumb grant_services_network_role for root module

- modules/gsuite_enabled/versions.tf
- modules/svpc_service_project/versions.tf
- versions.tf
Closes #623
This change will enable explicit provider configuration, e.g:
```terraform
provider "google" {
alias = "service_account"
credentials = var.service_account_credentials
}
module "project-factory" {
providers = {
google = google.service_account
}
}
```
I chose the version constraints (`>= 3.50, < 4.0`) because that is the minimum required to meet every nested module's requirements. `modules/shared_vpc_access` requires `>= 3.43, <4.0` but `3.43` would not meet the `>= 3.50, < 4.0` requirements of `modules/core_project_factory`. 
I ran some checks and it's already not possible to use any part of this project with a version less than `3.50` because there's already an implicit dependency on `>= 3.50` -- this change just makes it explicit, _everything_ makes use of something with a …
> fix: Allow explicit Provider configuration in Module

- modules/budget/outputs.tf
When running `terraform plan -refresh-only` and `var.create_budget` turns from `false` to `true` (via passing a non-null `budget_amount` in [`create_budget = var.budget_amount != null`](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/main.tf#L90) this fails with the message:
```
│ Error: Invalid index
│
│   on .terraform/modules/project.project-factory/modules/budget/outputs.tf line 19, in output "name":
│   19:   value       = var.create_budget ? google_billing_budget.budget[0].name : ""
│     ├────────────────
│     │ google_billing_budget.budget is empty tuple
│
│ The given key does not identify an element in this collection value: the
│ collection has no elements.
```
Seems related to https://github.com/hashicorp/terraform/issues/23222
Run on: …
> Wrap budget_name output with length check 

- modules/core_project_factory/main.tf
Setting "depends_on" will execute the correct destroy sequence required for the **VPC-SC Perimeter Resource attachment** and the **Default Service Account**
[Issue 690](https://github.com/terraform-google-modules/terraform-google-project-factory/issues/690)
> BUG #690 Fix - VPC-SC SA destroy sequence

- helpers/setup-sa.sh
Convert setup-sa.sh to use billing accounts add-iam-policy-binding for billing account setup.  Prevents possible get/set race condition, and removes dependency on uname check.
> feat: setup-sa.sh use add-iam-policy-binding

- test/fixtures/vpc_sc_project/main.tf
Use the Access Perimeter Submodule's release rather than the repo's head in test.  #685
> fix: use module release rather than repo head

- examples/fabric_project/README.md
- examples/fabric_project/variables.tf
fix: add serviceusage.googleapis.com to default list of APIs to enable in fabric-project
Closes #710
> fix: add serviceusage API to fabric-project enable default list

- examples/project-hierarchy/main.tf
- test/fixtures/fabric_project/main.tf
- test/setup/main.tf
- test/setup/outputs.tf
fix!: test/setup/outputs.folder_id returns `folder_id` instead of `folders/{folder_id}`
Closes #711
> fix!: test/setup/outputs.folder_id returns folder_id

- examples/budget_project/main.tf
- examples/essential_contacts/main.tf
- examples/shared_vpc/main.tf
- test/fixtures/vpc_sc_project/main.tf
- Add activation of cloudresourcemanager API to budget_projects example. Closes #715 
- Add activation of cloudresourcemanager API to shared_vpc example. Closes #717 
- Add activation of serviceusage API to essential_contacts example. Closes #718 
- Add activation of cloudresourcemanager API to vpc_sc_project example. Closes #719
> fix: add cloudresourcemanager api to examples

- examples/budget_project/main.tf
- add billingbudgets API to budget example. Fixes #720
> chore: add billingbudgets API to budget

- modules/shared_vpc_access/README.md
- modules/shared_vpc_access/main.tf
These comments were removed in https://github.com/terraform-google-modules/terraform-google-project-factory/pull/567 and the code was confusing without them.
> chore: update code comments and docs to be aligned with code

- README.md
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- variables.tf
Add support to project cloud storage public access prevention
New variable: bucket_pap
possible values: "enforced" or "inherited" (default)
public access prevention support implemented by PR https://github.com/hashicorp/terraform-provider-google-beta/pull/3919, but missing associated documentation as mentioned in the link. Also only in google-beta, although PAP is no longer beta.
> Add support to project cloud storage public access prevention

- README.md
- main.tf
- modules/budget/README.md
- modules/budget/main.tf
- modules/budget/variables.tf
- modules/budget/versions.tf
- variables.tf
- versions.tf
> feat!: Add support for custom time periods in budget module

- README.md
- examples/budget_project/main.tf
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- test/integration/budget/controls/budget.rb
- variables.tf
* Add `random_project_id_length` which also enables a larger collusion domain from [0-9a-f]4 to [0-9a-z]n.
> feat: add random_project_id_length

- CONTRIBUTING.md
- Makefile
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- modules/shared_vpc_access/README.md
- modules/shared_vpc_access/main.tf
- modules/shared_vpc_access/variables.tf
- test/fixtures/shared_vpc_no_subnets/main.tf
- test/integration/shared_vpc_no_subnets/controls/gcloud.rb
- test/setup/outputs.tf
- test/setup/variables.tf
Added datastream [permission requirements](https://cloud.google.com/datastream/docs/create-a-private-connectivity-configuration) in shared_vpc_access module #787 
Fix `missing profile_id` in test for vpc-sc-project-local test #780
> feat: added datastream support in shared_vpc_access module

- CONTRIBUTING.md
- Makefile
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- test/setup/outputs.tf
- test/setup/variables.tf
This is a partial rollback of: #788.
The reason #780 was failing was due to lack of permissions for the cloudbuild service agent on the test org. Giving that SA access context reader permission [fixes](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1420) this.
> fix: removes policy id env var from int build config

- examples/gke_shared_vpc/README.md
- modules/budget/main.tf
When having a lot of projects the data resource makes the plan hard to read. To fix that only read the project data if it is needed.
> feat(budget): Only read project data when budget will be created

- Makefile
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- modules/core_project_factory/outputs.tf
- modules/gsuite_enabled/main.tf
- modules/gsuite_group/main.tf
- test/fixtures/shared_vpc_no_subnets/main.tf
pin to dev-tools minor for any future tflint requirements, etc
> fix: lint for dev-tools and CI

- modules/shared_vpc_access/main.tf
Update the shared_vpc_access module to grant the notebooks.googleapis.com SA the appropriate network roles. It needs roles/compute.networkUser on the subnets being shared.
> fix: shared_vpc_access - Grant notebooks.googleapi.com SA the networkUser role

- README.md
- build/int.cloudbuild.yaml
- examples/tags_project/README.md
- examples/tags_project/main.tf
- examples/tags_project/outputs.tf
- examples/tags_project/variables.tf
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/outputs.tf
- modules/core_project_factory/variables.tf
- outputs.tf
- test/integration/tags_project/tags_project_test.go
- test/setup/iam.tf
- test/setup/outputs.tf
- test/setup/tags.tf
- variables.tf
> feat: support optional tag binding

- metadata.yaml
PR to address https://github.com/terraform-google-modules/terraform-google-project-factory/issues/904
vpc_service_control_attach_dry_run was not previously included in metadata file so it was not exposed to the module
> chore(metadata): add vpc_service_control_attach_dry_run 

- main.tf
- modules/svpc_service_project/main.tf
> fix: switch svpc access to explicit dep on service enablement

- README.md
- docs/upgrading_to_project_factory_v17.0.md
- examples/app_engine/main.tf
- examples/budget_project/main.tf
- examples/essential_contacts/main.tf
- examples/fabric_project/main.tf
- examples/gke_shared_vpc/main.tf
- examples/quota_project/main.tf
- examples/shared_vpc/main.tf
- examples/simple_project/main.tf
- examples/tags_project/main.tf
- modules/core_project_factory/variables.tf
- modules/fabric-project/README.md
- modules/fabric-project/variables.tf
- modules/svpc_service_project/README.md
- modules/svpc_service_project/main.tf
- modules/svpc_service_project/variables.tf
- test/fixtures/minimal/main.tf
- test/fixtures/vpc_sc_project/main.tf
- variables.tf
- align to TPGv6 default (unblocks https://github.com/terraform-google-modules/terraform-google-project-factory/pull/933)
> feat!: deletion_policy PREVENT as default

- main.tf
- modules/svpc_service_project/main.tf
This is a followup of https://github.com/terraform-google-modules/terraform-google-project-factory/pull/934/commits/c1a7e1398c00abd050199aa7ac5db2e2be541860
Fixes #946
> fix: include the APIs with identities created in the shared VPC config #946

- modules/shared_vpc_access/main.tf
As [documented](https://cloud.google.com/data-fusion/docs/how-to/configure-private-service-connect#roles-permissions), the Data Fusion service agent requires the `roles/compute.networkViewer` role.
The `local.apis` needed some refactoring to allow having different roles assigned per service agent because Data Fusion only requires `networkViewer` and the existing service agents require `networkUser`
This fixes #948
> fix(shared_vpc_access): Add support to grant required IAM permissions for Data Fusion service agent

- README.md
- main.tf
- metadata.yaml
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- variables.tf
Enable setting a description for the default service account in `core_project_factory`. I am implementing an organization policy that requires our SA's have descriptions and we rely on this SA for new projects, so this minor feature request would help us there. The default is null to prevent changing existing resources.
> feat(core_project_factor): enable setting a description for the default service account
