- helpers/setup-sa.sh
This pr adds enabling the required API Services to the helper script
> enable apis in setup

- README.md
- docs/TROUBLESHOOTING.md
This pull request is based on #50.
> Update TROUBLESHOOTING.md for API activation through helper script

- .gitignore
- README.md
- examples/app_engine/main.tf
- examples/gke_shared_vpc/main.tf
- examples/group_project/main.tf
- examples/project-hierarchy/main.tf
- examples/simple_project/main.tf
- helpers/init_debian.sh
- helpers/setup-sa.sh
- test/fixtures/full/main.tf
- test/fixtures/minimal/main.tf
This branch comprises fixes to the init_debian.sh helper script.
> Fix init_debian.sh

- test/fixtures/full/main.tf
- test/fixtures/full/terraform.tfvars.example
- test/integration/full/controls/gsuite.rb
- test/integration/full/controls/project-factory.rb
- test/integration/full/controls/shared-vpc.rb
This branch addresses issues discovered during my review of #67.
> Supplement to "Fixup errors in test-kitchen test coverage"

- Makefile
- build/docker/kitchen_terraform/Dockerfile
> Use gem bundle when executing Kitchen-Terraform

- build/docker/kitchen_terraform/Dockerfile
> Install gcloud Alpha commands component

- helpers/migrate.py
- test/helpers/test_migrate.py
This pull request adds a first pass of a migration script that can detect project-factory resources in a state file and intelligently rename them.
> Add migration script for G Suite refactor

- helpers/migrate.py
This branch fixes the issues surfaced in #94.
> Fix Migration Script

- helpers/init_debian.sh
- helpers/release-new-version.sh
- helpers/setup-sa.sh
- test/make.sh
This branch addresses violations of the `make check_shell` target.
> Fix violations of `make check_shell`

- README.md
- main.tf
- modules/core_project_factory/README.md
- modules/core_project_factory/main.tf
- modules/core_project_factory/outputs.tf
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/outputs.tf
- outputs.tf
- test/fixtures/full/README.md
- test/fixtures/full/main.tf
- test/fixtures/minimal/README.md
This branch fixes the issue of counts which can not be computed.
> Fix count computation

- helpers/combine_docfiles.py
- helpers/migrate.py
- modules/core_project_factory/scripts/preconditions/preconditions.py
- test/helpers/test_migrate.py
- test/make.sh
This branch fixes the issues raised by `make check_python`.
> Fix check_python issues

- README.md
> Fix references to preconditions checker script

- modules/gsuite_enabled/main.tf
- modules/gsuite_group/main.tf
- modules/gsuite_group/outputs.tf
- modules/gsuite_group/variables.tf
- test/ci_integration.sh
Don't create a resource in the core project factory module that pulls in the gsuite provider.
> Fix regression in v1.1.0

- CHANGELOG.md
This branch adds the entry for 2.1.2 to the Changelog.
> [ci skip] Add 2.1.2 to Changelog

- modules/core_project_factory/README.md
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
I believe this resolves issue #167
> feat: add ability to select location for project bucket

- Makefile
the generate_docs target has been removed.
> generate_docs has been removed from the default make target

- modules/core_project_factory/scripts/preconditions/preconditions.py
> Allow personal credentials

- README.md
> Update Terraform version to 1.11.x

- README.md
- test/fixtures/shared_vpc_no_subnets/terraform.tfvars
There was an issue related to trying variables usage before variables creation in test/ci-integration.sh
> Some fixes for integration tests

- main.tf
- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/variables.tf
> Pass through apis_authority

- modules/core_project_factory/scripts/preconditions.sh
Addresses #191 
Signed-off-by: Brian Menges <mengesb@gmail.com>
> Attempt to install python requirements

- Makefile
- docs/TROUBLESHOOTING.md
- examples/app_engine/main.tf
- examples/app_engine/outputs.tf
- examples/shared_vpc/main.tf
- helpers/terraform_docs
- helpers/terraform_validate
- modules/core_project_factory/scripts/preconditions/preconditions.py
- modules/fabric-project/main.tf
- modules/gsuite_enabled/README.md
- test/integration/full/controls/app-engine.rb
- test/make.sh
This PR is a sequence of patches intended to get CI tests and documentation working with Terraform 0.12.
The intent is to test out the upgrade process from an end-user perspective, this PR captures small steps toward that goal.
> Fix tests failing with Terraform 0.12

- examples/shared_vpc/main.tf
Fixes https://github.com/terraform-google-modules/terraform-google-project-factory/issues/292
> removed bug workaround in shared_vpc example

- examples/gke_shared_vpc/main.tf
- examples/group_project/main.tf
- examples/project-hierarchy/main.tf
- examples/shared_vpc/main.tf
- examples/simple_project/main.tf
- modules/gsuite_enabled/README.md
- modules/project_services/examples/project_services/main.tf
- test/fixtures/full/main.tf
- test/fixtures/minimal/main.tf
- test/fixtures/shared_vpc_no_subnets/main.tf
- test/setup/versions.tf
Fixes the provider version in order to ensure tests pass and teardown succeeds.
Once this merges, I'll update my other PR's, which have some of the same changes, and all of the older PRs should start passing again, once they are rebased/merged
> update provider versions to fixed version, everywhere

- helpers/setup-sa.sh
Update the helper script to grant the necessary roles to the Seed Service. Add optional roles/resourcemanager.folderViewer on the folder where the project will be created.
> Script Helper Update

- modules/gsuite_group/main.tf
- modules/gsuite_group/variables.tf
> Fix organization permission requirement

- CHANGELOG.md
- README.md
- docs/upgrading_to_project_factory_v6.0.md
> Add upgrade docs for 6.0

- modules/core_project_factory/main.tf
- test/setup/versions.tf
> Improve default empty values for org and folder in core submodule

- helpers/setup-sa.sh
Replaces https://github.com/terraform-google-modules/terraform-google-project-factory/pull/266
> Make project check more efficient

- .kitchen.yml
- examples/app_engine/README.md
- examples/app_engine/main.tf
- examples/app_engine/outputs.tf
- examples/app_engine/variables.tf
- modules/app_engine/outputs.tf
- modules/app_engine/variables.tf
- test/fixtures/app_engine/main.tf
- test/fixtures/app_engine/outputs.tf
- test/fixtures/app_engine/variables.tf
- test/fixtures/full/main.tf
- test/integration/app_engine/controls/app-engine.rb
- test/integration/app_engine/inspec.yml
> Modify app engine example, fixture, obj for healthchecks

- CHANGELOG.md
- README.md
- docs/TROUBLESHOOTING.md
- examples/simple_project/README.md
- examples/simple_project/variables.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/scripts/modify-service-account.sh
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/variables.tf
- modules/shared_vpc/variables.tf
- variables.tf
> Fix typo. Update Changelog

- modules/core_project_factory/main.tf
Removing use of compact and subnet name validation seems to fix #362 more cleanly.
> Fix: #362 allow users to supply dynamically generated list of subnets

- examples/app_engine/main.tf
- examples/budget_project/main.tf
- examples/fabric_project/main.tf
- examples/gke_shared_vpc/main.tf
- examples/group_project/main.tf
- examples/project-hierarchy/main.tf
- examples/project_services/main.tf
- examples/shared_vpc/main.tf
- examples/simple_project/main.tf
- modules/fabric-project/versions.tf
- test/fixtures/full/main.tf
- test/fixtures/minimal/main.tf
- test/fixtures/shared_vpc_no_subnets/main.tf
- test/setup/main.tf
Also fixes the core_project_factory that still pointed to 2.x
> Bump provider versions

- modules/core_project_factory/scripts/preconditions/preconditions.py
> Add doc explaining preconditions.py

- .kitchen.yml
- Makefile
- examples/shared_vpc/README.md
- examples/shared_vpc/main.tf
- examples/shared_vpc/outputs.tf
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/variables.tf
- modules/shared_vpc/variables.tf
- test/fixtures/dynamic_shared_vpc/outputs.tf
- test/integration/dynamic_shared_vpc/controls/svpc.rb
- test/integration/dynamic_shared_vpc/inspec.yml
- variables.tf
Fixes #378 and adds a test case to prevent regressions.
> Fix issue with empty subnet defaults and Shared VPC

- helpers/setup-sa.sh
Give an option to create a custom service account name in the helper script.
> custom service account name

- README.md
- examples/project_services/main.tf
- examples/simple_project/main.tf
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- modules/project_services/README.md
- modules/project_services/main.tf
- modules/project_services/outputs.tf
- modules/project_services/variables.tf
- variables.tf
Fix #448 
This won't work till google-beta provider is released with the service identity resource next Monday.
> feat: Add service identity

- modules/project_services/main.tf
- modules/project_services/variables.tf
> Fix: Restore usage of var.enable_apis variable for project services submodule

- modules/shared_vpc_access/README.md
- modules/shared_vpc_access/main.tf
- modules/shared_vpc_access/variables.tf
Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/723
> Support optionally grant GKE SA network admin on VPC host project

- helpers/setup-sa.sh
> fix: Add billingbudgets.googleapis.com to precondition script.

- modules/core_project_factory/main.tf
Handles https://github.com/terraform-google-modules/terraform-google-project-factory/issues/497
> Adds count variable to does not create the resource when value is keep

- README.md
- modules/core_project_factory/outputs.tf
- outputs.tf
exposes service identity sa emails via root module
> feat: expose service identity sa emails

- modules/project_services/README.md
I have been using an old version because I only read this readme. :(
> chore(docs): update version in README.md

- modules/budget/main.tf
fixes https://github.com/terraform-google-modules/terraform-google-project-factory/issues/555
> fix: explicit depends on for budget project data source

- modules/shared_vpc_access/main.tf
Permissions required to allow cloud composer environment on the shared vpc.
> feat: Cloud composer environment on the shared vpc.

- README.md
Fixes #579 
Signed-off-by: Jai Govindani <jai@honestbank.com>
> docs(readme): update helpers/setup-sa.sh parameters

- README.md
- docs/upgrading_to_project_factory_v11.0.md
- examples/gke_shared_vpc/README.md
- examples/gke_shared_vpc/main.tf
- examples/gke_shared_vpc/variables.tf
- examples/group_project/README.md
- examples/group_project/main.tf
- examples/group_project/variables.tf
- examples/project-hierarchy/README.md
- examples/project-hierarchy/main.tf
- examples/project-hierarchy/variables.tf
- examples/simple_project/README.md
- examples/simple_project/main.tf
- examples/simple_project/variables.tf
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/variables.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/main.tf
- modules/gsuite_enabled/variables.tf
- modules/svpc_service_project/README.md
- modules/svpc_service_project/main.tf
- modules/svpc_service_project/variables.tf
- variables.tf
- fixes #523 
- Adds upgrade guide for 11.0 release
> fix: remove unused vars, add upgrade guide

- README.md
Adding relavent warning notes under the caveats section of the readme file. Address #612
> Readme update: deleting default SA considerations

- helpers/setup-sa.sh
> fix: grant roles/billing.viewer to the seed service account in bootstrap helper

- README.md
> chore: remove credentials_path from docs

- modules/fabric-project/main.tf
> fix: ConflictsWith org_id & folder_id in fabric-project

- build/int.cloudbuild.yaml
similar to https://github.com/terraform-google-modules/terraform-google-vm/pull/219
Also removed GCLOUD_TF_DOWNLOAD since we no longer use the gcloud module
> chore: serial init for build

- test/setup/main.tf
- test/setup/versions.tf
chore: add wait to test/setup to reduce test flakes
feat: update test/setup to pfactory 13.0
> chore: add wait to test/setup to reduce test flakes

- modules/project_services/README.md
bumping manually due to release please bug b/194500618
> chore: fix version in readme

- README.md
- examples/app_engine/README.md
- examples/app_engine/variables.tf
- examples/essential_contacts/README.md
- examples/essential_contacts/variables.tf
- modules/app_engine/variables.tf
- modules/core_project_factory/outputs.tf
- modules/core_project_factory/versions.tf
- modules/essential_contacts/README.md
- modules/essential_contacts/variables.tf
- modules/gsuite_enabled/README.md
- modules/gsuite_enabled/outputs.tf
- modules/gsuite_enabled/variables.tf
- modules/project_services/README.md
- modules/project_services/variables.tf
- modules/svpc_service_project/variables.tf
- outputs.tf
Mostly types, description and one unused var in an example detected by tflint. https://github.com/terraform-google-modules/terraform-google-project-factory/pull/767#issuecomment-1316021492 has the details
> chore: fixes for issues reported by tflint

- modules/shared_vpc_access/main.tf
According to https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-shared-vpc#enabling_and_granting_roles
roles/compute.networkUser access on SERVICE_PROJECT_NUM@cloudservices.gserviceaccount.com in subnetwork is missing in the terraform module
current terraform module fails to deploy a usable cluster, and system related pods doesn't come up
This fix give the required access which is needed
> fix: add service account access for gke in shared vpc

- README.md
- docs/upgrading_to_project_factory_v15.0.md
- main.tf
- modules/core_project_factory/main.tf
- modules/core_project_factory/outputs.tf
- modules/core_project_factory/variables.tf
- modules/core_project_factory/versions.tf
- outputs.tf
- variables.tf
- versions.tf
> feat(TPG >5.22)!: added vpc sc dry run mode option

- modules/core_project_factory/main.tf
> fix: ignore changes on firebase label

- modules/shared_vpc_access/main.tf
The Apache Kafka Service Agent's role should be granted on the project not on the subnet.
The service needs to create a zone that will contain the bootstrap and broker endpoint addresses.
> fix(shared_vpc_access): grant GMK service agent role on host project
